name: Deploy The Web App
on:
  push:
    branches:
      - master

jobs:
  check-version:
    name: Check Package Version Changes
    runs-on: ubuntu-latest
    steps:
      # Check if there is a change in the package.json version.
      # If so, create a new release. If not, other jobs will not run b/c of `if:` statement.
      - name: Checkout Master
        uses: actions/checkout@master
        with:
          fetch-depth: 0
      - name: Create GitHub Release
        uses: justincy/github-action-npm-release@master
        id: release
      - name: Check if should deploy
        # If
        if: ${{ steps.release.outputs.released != 'true' }}
        run: exit 1

  deploy:
    name: Deploy
    needs: check-version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      # Replace Firebase secret admin key in key json file
      - uses: jwsi/secret-parser@master
        with:
          filename: firebase-service-account-key.json
          secret-name: FIREBASE_PRIVATE_KEY
          secret-value: ${{ secrets.FIREBASE_PRIVATE_KEY }}

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy Frontend
        uses: w9jds/firebase-action@master
        with:
          args: deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
